### ISSUE TITLE
[Documentation] Missing filter descriptions

### ISSUE THREAD

**Issue by drunkel** [michaelmulley/openparliament#44]
Hi!

Can we please get the descriptions/example usage for the filters without one on http://api.openparliament.ca/bills/ and http://api.openparliament.ca/committees/ (if these are used).

Thanks!

**Comment by rhymeswithcycle** [comment]
Every filter listed on the API pages should work.

On committees, `session` is the Parliamentary session, in the same format as on a committee resource. So `session=40-1` will show you the committees active during the 1st session of the 40th Parliament.

On bills, `status_code` is a field provided by Parliament's XML data, and they haven't provided a comprehensive list, but all the values I've seen so far are listed at https://github.com/rhymeswithcycle/openparliament/blob/master/parliament/bills/models.py#L70

`sponsor_politician_membership` is a filter on that value in a bill resource. A "membership" is a politician, elected in a specific riding with a specific party. So someone who runs in a different riding in different elections, or who changes parties, will have more than one membership resource (but still only one politician resource).
