### ISSUE TITLE
Wrong link to parliament site in the statement section

### ISSUE THREAD

**Issue by jslap** [michaelmulley/openparliament#47]
In the statement section from the debates, when clicking on "Link & Sharing", the option to go the the link to this statement in the parliament site is linking to a broken link.
It seems that the format a the link has changed.
The current link in openParliament is : http://www.ourcommons.ca/en/parliamentary-business#Int-10230856
The link that should be there is: http://www.ourcommons.ca/DocumentViewer/en/42-1/house/sitting-318/hansard#Int-10230856

**Comment by michaelmulley** [comment]
I'd neglected the issues page here, but this was fixed a while back -- thanks!
